### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by JithinKS97** [dynamic-learning/next-client#71]
Adding authentication by integrating with apis provided by the backend. Also need to add github and google authentications.

**Comment by JithinKS97** [comment]
Refer https://jolvera.dev/posts/user-authentication-with-nextjs

**Comment by JithinKS97** [comment]
See https://next-auth.js.org/

**Comment by JithinKS97** [comment]
As a preliminary step, after authentication operation(from Login form), we can provide an ```isAuthenticated``` prop to every page component using which we can disable or enable operations that can be performed on the page.
Also, there are two kinds of authenticated users, admin, and normal. Only admin user has the permission to add simulation in the simulation repo.
Once we start the implementation, we can have more discussion on the same.

**Comment by Aswin40** [comment]
@JithinKS97  The `isAuthenticated `prop must be checked each time the a user access a page.We should have some way to verify that the user is currently authenticated to access the page or authorised to perform an action on the page.

**Comment by JithinKS97** [comment]
@Aswin40 Yes, currently I'm thinking of using a custom hook to provide that information. It will be like
`const { isAuthenticated, permissions } = useAuth()`
`isAuthenticated` and `permissions` can be used to enable/disable and hide options.

**Comment by JithinKS97** [comment]
I'm looking forward for using this library https://next-auth.js.org/

**Comment by anandsimmy** [comment]
just a thought. what about keeping 'isAuthenticated' value at the top level (redux store) and be accessed by child component

**Comment by Aswin40** [comment]
@anandsimmy A clarification on the above comment. If we are going to store the isAuthenticated value at top level redux store,Still we need to update the value for each loading of the page right. And that update of the value takes place either via an HOC or  within the page right?

**Comment by anandsimmy** [comment]
As its, a top-level component value is fetched on the mount and when a user is navigating between pages, the value remains the same. because only child components are changing based on the route and top-level stays intact. 'isAuthenticated' value can be changed in the usual fashion via a HOC. And I haven't tried custom hook pattern yet, but if that's a better approach then we can go forward with it

**Comment by Aswin40** [comment]
The HOC or custom hook pattern can be taken as a different question. But the authentication check must be performed while navigating between pages also right.Suppose the token expires  or is invalidated due to some event after logout. If the authentication is not checked in each page then the user will still have access to all the resource even without a token.

**Comment by anandsimmy** [comment]
@Aswin40 authentication check must be performed at navigation or whatever its if needed. but there isn't any need to update the value just for navigating. coming to your question, if the token expires or invalidated redux store is updated at the top level triggering  re-rendering of subscribed components
"If we are going to store the isAuthenticated value at top level redux store,Still we need to update the value for each loading of the page right."
I'm referring to this comment. There's no need to update the value when navigating to different pages, rather a check is only required.

**Comment by Aswin40** [comment]
Yes you are right.Understood your point.

**Comment by JithinKS97** [comment]
@anandsimmy @Aswin40 As of now, only the index page is connected to the redux store. If `isAuthenticated` is to be accessed on every page, we might need to bring that to `App` level.

I'm fine with either of the approach. But I think the hooks approach is more reusable and neat.

**Comment by anandsimmy** [comment]
ok..cool
